# stage 1
FROM python AS build
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

# stage 2 dev
FROM build AS development
COPY . .
CMD ["python3","main.py"]

# stage 3 prod
FROM build AS production
RUN pip install gunicorn
COPY . .
CMD ["gunicorn","system:app","-b 0.0.0.0:8000"]
