services:
  backend:
    build:
      context: .
      target: development  # Explicitly specify the development stage
    container_name: docker-test
    ports:
      - "5000:5000"
    environment:
      - URI=redis://redis:6379
    volumes:
      - .:/app ## bind

  redis:
    image: redis
    ports:
       - "6379:6379"
    container_name: docker-test-redis
    volumes:
      - .:/app