# apiVersion: v1
# kind: ReplicationController # it is old
apiVersion: apps/v1 # apps/v1 for replicaset
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    env: demo
spec:
  # template = Pod blueprint
  template:
    metadata:
      labels:
        env: pod-demo
    spec:
      containers:
        - name: nginx
          image: nginx

  replicas: 3
  # as part of the replica set
  # matching the labels of the pod will be managed by the replicaset
  selector:
    matchLabels:
      env: pod-demo
