apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: niginx
  name: niginx
spec:
  containers:
  - image: nginx
    name: niginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
