apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-room-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-backend
  
  template:
    metadata:
      labels:
        app: chat-backend
    
    spec:
      containers:
      - image: chat-room
        name: chat-room
        ports:
        - containerPort: 8000  # Exposing port 8000
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: chat-room-backend-svc
  
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 8000
  selector:
    app: chat-backend