apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: nginx-deployment
spec:
  template:
    metadata:
      labels:
        env: demo-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 5
  selector:
    matchLabels:
      env: demo-nginx